store:
  title: "Store Admin"
  endpoint: "admin-store"
  getItemId: "slug"
  createDefaults:
    defaultAmount: 0
  columns:
    - field: "slug"
    - field: "title"
    - field: "hide"
      render: "boolean"
  fields:
    - name: "slug"
      type: "text"
    - name: "title"
      type: "text"
    - name: "description"
      type: "text"
    - name: "summary"
      type: "text"
    - name: "defaultAmount"
      type: "number"
    - name: "details"
      type: "textarea"
    - name: "hide"
      label: "Hide Item"
      type: "boolean"
    - name: "options"
      type: "keyValueMap"
    - name: "supporters"
      type: "textList"

events:
  title: "Events Admin"
  endpoint: "admin-events"
  getItemId: "slug"
  columns:
    - field: "slug"
    - field: "title"
    - field: "hide"
      render: "boolean"
  fields:
    - name: "slug"
      type: "text"
    - name: "title"
      type: "text"
    - name: "description"
      type: "text"
    - name: "summary"
      type: "text"
    - name: "hide"
      label: "Hide Event"
      type: "boolean"
    - name: "organizers"
      type: "textList"

links:
  title: "Links Admin"
  endpoint: "admin-links"
  getItemId: "slug"
  columns:
    - field: "slug"
    - field: "title"
    - field: "hide"
      render: "boolean"
  fields:
    - name: "slug"
      type: "text"
    - name: "title"
      type: "text"
    - name: "summary"
      type: "text"
    - name: "href"
      type: "text"
    - name: "header"
      label: "Is Header"
      type: "boolean"
    - name: "hide"
      label: "Hide Link"
      type: "boolean"

forms:
  title: "Forms Admin"
  endpoint: "admin-forms"
  getItemId: "slug"
  createDefaults:
    width: 640
    height: 1000
  columns:
    - field: "slug"
    - field: "title"
    - field: "hide"
      render: "boolean"
  fields:
    - name: "slug"
      type: "text"
    - name: "title"
      type: "text"
    - name: "summary"
      type: "text"
    - name: "formId"
      label: "Form ID"
      type: "text"
    - name: "href"
      type: "text"
    - name: "formLink"
      type: "text"
    - name: "width"
      type: "number"
    - name: "height"
      type: "number"
    - name: "hide"
      label: "Hide Form"
      type: "boolean"

calendar:
  title: "Calendar Admin"
  endpoint: "admin-calendar"
  getItemId: "name"
  transforms: "calendar"
  globalFields:
    - name: "months"
      type: "number"
  columns:
    - field: "name"
    - field: "matches"
      render: "calendarMatches"
    - field: "limit"
    - field: "hideSummary"
      render: "boolean"
  fields:
    - name: "name"
      type: "text"
    - name: "matches"
      type: "text"
    - name: "notMatches"
      type: "text"
    - name: "limit"
      type: "number"
    - name: "hideSummary"
      type: "boolean"

link_mappings:
  title: "Link Mappings Admin"
  endpoint: "admin-link-mappings"
  getItemId: "type"
  editOnly: true
  transforms: "linkMappings"
  columns:
    - field: "type"
    - field: "default"
  fields:
    - name: "type"
      type: "text"
    - name: "default"
      type: "text"
    - name: "mappings"
      label: "Mappings (Label -> Regex)"
      type: "textKeyValueMap"

home:
  title: "Home Admin"
  endpoint: "admin-home"
  getItemId: "source"
  transforms: "home"
  reorderable: true
  globalFields:
    - name: "heroMarkdown"
      label: "Hero Markdown"
      type: "textarea"
    - name: "calendars"
      label: "Calendar Filters"
      type: "textList"
  columns:
    - field: "source"
    - field: "cardTitleField"
      header: "Card Title Field"
  fields:
    - name: "source"
      type: "select"
      options: ["store", "events", "links"]
    - name: "title"
      type: "text"
    - name: "cardTitleField"
      label: "Card Title Field"
      type: "select"
      options: ["title", "description"]
    - name: "cardHrefPrefix"
      label: "Card Href Prefix"
      type: "text"
    - name: "cardHrefField"
      label: "Card Href Field"
      type: "select"
      options: ["href"]
